[package]
name = "sys_info_cli"
version = "0.1.0"
edition = "2021"


[dependencies]
sysinfo = "0.30.5"


[[bin]]
name = "sys-info"
path = "src/main.rs"

[[bin]]
name = "install"
path = "install/src/main.rs"